version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    tty: true
    stdin_open: true
    restart: always
    container_name: rabbitmq
